import { GoogleGenAI, GenerateContentResponse, Type } from "@google/genai";

export interface AIConfig {
  apiKey: string;
  model: string;
  imageModel: string;
}

const DEFAULT_RETRY_ATTEMPTS = 3;
const RETRY_DELAY_MS = 1000;

async function wait(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function withRetry<T>(fn: () => Promise<T>, attempts = DEFAULT_RETRY_ATTEMPTS): Promise<T> {
  let lastError: any;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastError = err;
      if (i < attempts - 1) {
        await wait(RETRY_DELAY_MS * Math.pow(2, i));
      }
    }
  }
  throw lastError;
}

export async function discoverNiches(config: AIConfig, count = 5): Promise<any[]> {
  const ai = new GoogleGenAI({ apiKey: config.apiKey });
  
  return withRetry(async () => {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: config.model,
      contents: `Generate ${count} high-potential Print-on-Demand micro-niches for 2026. 
      Focus on scientific, technical, or futuristic themes.
      Return ONLY a JSON array of objects with: name, score (0-100), competition (low/medium/high), demand (low/medium/high), profitability (0-100), trend (0-100), category.`,
      config: { 
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING },
              score: { type: Type.NUMBER },
              competition: { type: Type.STRING },
              demand: { type: Type.STRING },
              profitability: { type: Type.NUMBER },
              trend: { type: Type.NUMBER },
              category: { type: Type.STRING }
            },
            required: ["name", "score", "competition", "demand", "profitability", "trend", "category"]
          }
        }
      }
    });

    return JSON.parse(response.text || "[]");
  });
}

export async function generateDesign(config: AIConfig, nicheName: string, style: string): Promise<{ imageUrl: string; prompt: string }> {
  const ai = new GoogleGenAI({ apiKey: config.apiKey });
  const prompt = `Professional POD design for "${nicheName}". Style: ${style}. Clean, minimalist, high contrast, vector aesthetic. No text unless requested.`;

  return withRetry(async () => {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: config.imageModel,
      contents: prompt,
    });

    let imageUrl = "";
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!imageUrl) throw new Error("No image generated by the model.");
    return { imageUrl, prompt };
  });
}

export async function runAutomation(config: AIConfig, prompt: string, systemInstruction?: string): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: config.apiKey });
  
  return withRetry(async () => {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: config.model,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction || "You are a scientific automation assistant. Provide clear, data-driven, and actionable insights.",
      },
    });
    return response.text || "No response generated.";
  });
}
